name: Documentation

on:
  workflow_call:

jobs:
  build_doc:
    # This build is to make PR comments for the sphinx warning and check if
    # web links are not broken 
    name: Check links and make PR comments
    runs-on: ubuntu-latest
    env:
      DOCS_PATH: ./doc/_build/html/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Fetch tags upstream
        if: ${{ github.repository_owner != 'hyperspy' }}
        # Needs to fetch the tags from upstream to get the
        # correct version with setuptools_scm
        run: |
          git remote add upstream https://github.com/hyperspy/${{env.REPOSITORY_NAME}}.git
          git fetch upstream --tags

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install build docs
        shell: bash -l {0}
        run: |
          pip install .'[doc]'
      
      # Add sphinx warnings as PR comments
      - uses: sphinx-doc/sphinx-problem-matcher@master

      - name: Build documentation
        shell: bash -l {0}
        run: |
          cd doc
          make SPHINXOPTS="-W --keep-going" html

      - uses: actions/upload-artifact@v3
        with:
          path: ${{ env.DOCS_PATH }}
          name: docs_html

      - name: Check links
        shell: bash -l {0}
        run: |
          cd doc
          make linkcheck

  push_doc:
    # This build is to push changes to gh-pages branch (https://hyperspy.org/$)
    needs: build_doc
    name: Push to gh-pages
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'hyperspy' }}
    permissions:
      # needs write permission to push the docs to gh-pages
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages

      - uses: actions/download-artifact@v3
        with:
          name: docs_html
          path: .

      - name: list files
        run: |
          ls

      - name: Git status
        run: |
          git status
          git status -s
          if [[ $(git status -s) ]]; then
            HAS_CHANGES='true'
          else
            HAS_CHANGES='false'
          fi
          echo "HAS_CHANGES=${HAS_CHANGES}" >> $GITHUB_ENV

      - name: Commit files
        # Skip when there is nothing to commit
        if: ${{ env.HAS_CHANGES == 'true' }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update docs build" -a

      - name: Push changes
        if: ${{ env.HAS_CHANGES == 'true' }}
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
