name: Build documentation

on:
  workflow_call:

jobs:
  build:
    # This build is to make PR comments for the sphinx warning and check if
    # web links are not broken 
    name: Check links and make PR comments
    runs-on: ubuntu-latest
    env:
      DOCS_PATH: ./doc/_build/html/
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Fetch tags upstream
        if: ${{ github.repository_owner != 'hyperspy' }}
        # Needs to fetch the tags from upstream to get the
        # correct version with setuptools_scm
        run: |
          git remote add upstream https://github.com/hyperspy/${{env.REPOSITORY_NAME}}.git
          git fetch upstream --tags

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install build docs
        shell: bash -l {0}
        run: |
          pip install .'[doc]'
      
      # Add sphinx warnings as PR comments
      - uses: sphinx-doc/sphinx-problem-matcher@master

      - name: Build documentation
        shell: bash -l {0}
        run: |
          cd doc
          make SPHINXOPTS="-W --keep-going" html

      - uses: actions/upload-artifact@v3
        with:
          path: ${{ env.DOCS_PATH }}
          name: doc_html

      - name: Check links
        shell: bash -l {0}
        run: |
          cd doc
          make linkcheck
