name: Build documentation

on:
  workflow_call:
    inputs:
      doc_path:
        description: 'The path to the folder containing the doc'
        default: './doc'
        type: string
      doc_build_path:
        description: 'The path to the folder containing the build of the doc'
        default: './doc/_build/html/'
        type: string
      install_dependencies_only:
        description: 'Only install dependencies listed in `requirement.txt` using pip'
        default: false
        type: boolean
      pip_extra_doc:
        description: 'The name of the pip extra to install the doc'
        default: 'doc'
        type: string
      install_package_ubuntu:
        description: 'Packages to install in ubuntu'
        default: ''
        type: string
      doctest:
        description: 'Run doctest'
        default: false
        type: boolean
      use_xvfb:
        description: 'Whether to install and setup xvfb and pyqt for build the documentation'
        # if empty string, the current repository name is used
        default: false
        type: boolean

jobs:
  build:
    # This build is to make PR comments for the sphinx warning and check if
    # web links are not broken 
    name: Check links and make PR comments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Fetch tags upstream
        if: ${{ github.repository_owner != 'hyperspy' }}
        # Needs to fetch the tags from upstream to get the
        # correct version with setuptools_scm
        run: |
          git remote add upstream https://github.com/hyperspy/${{env.REPOSITORY_NAME}}.git
          git fetch upstream --tags

      - name: Install package in Ubuntu
        if: ${{ inputs.install_package_ubuntu }}
        run : |
          sudo apt-get update
          sudo apt-get install ${{ inputs.install_package_ubuntu }}

      - name: Install Ubuntu packages for Qt
        if: ${{ inputs.use_xvfb }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install libxcb-icccm4
          sudo apt-get install libxcb-image0
          sudo apt-get install libxcb-keysyms1
          sudo apt-get install libxcb-randr0
          sudo apt-get install libxcb-render-util0
          sudo apt-get install libxcb-xinerama0
          sudo apt-get install xvfb

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install library
        if: ${{ inputs.install_dependencies_only != true }}
        shell: bash -l {0}
        run: |
          pip install .'[${{ inputs.pip_extra_doc }}]'

      - name: Install dependencies
        if: ${{ inputs.install_dependencies_only }}
        shell: bash -l {0}
        run: |
          pip install -r requirements.txt

      - name: Run doctest
        shell: bash -l {0}
        if: ${{ inputs.doctest }}
        run: |
          cd ${{ inputs.doc_path }}
          pytest --doctest-modules --doctest-glob="*.rst" -n 2 -v

      # Add sphinx warnings as PR comments
      - uses: sphinx-doc/sphinx-problem-matcher@master

      - name: Build documentation
        if: ${{ inputs.use_xvfb != true }}
        shell: bash -l {0}
        run: |
          cd ${{ inputs.doc_path }}
          make SPHINXOPTS="-W --keep-going" html

      - name: Build documentation (with xvfb)
        if: ${{ inputs.use_xvfb }}
        run: |
          cd ${{ inputs.doc_path }}
          xvfb-run make SPHINXOPTS="-W --keep-going" html

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ inputs.doc_build_path }}
          name: doc_html

      - name: Check links
        if: ${{ always() }}
        shell: bash -l {0}
        run: |
          cd ${{ inputs.doc_path }}
          make linkcheck
