name: Push Documentation (Preview)
# preview feature of actions/deploy-pages not available publicly yet

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'The name of the github artifact containing the doc'
        # if empty string, the current repository name is used
        default: 'doc_html'
        type: string

jobs:
  deploy:
    name: "Pages Preview"
    runs-on: ubuntu-latest
    permissions:
      # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ inputs.artifact_name }}
          preview: "true"
